DROP TABLE IF EXISTS MEMBER;
CREATE TABLE MEMBER (
     M_SEQ      INTEGER PRIMARY KEY AUTO_INCREMENT,
     M_ID       VARCHAR(50) NOT NULL,
     M_NAME     VARCHAR(50)  NOT NULL,
     PRIMARY KEY(M_SEQ)
);
CREATE UNIQUE INDEX UK_MEMBER_MID ON MEMBER (M_ID);

DROP TABLE IF EXISTS ROOM;
CREATE TABLE ROOM (
     R_SEQ      INTEGER PRIMARY KEY AUTO_INCREMENT,
     R_ID       VARCHAR(50) NOT NULL,
     PRIMARY KEY(R_SEQ)
);
CREATE UNIQUE INDEX UK_ROOM_RID ON ROOM (R_ID);

DROP TABLE IF EXISTS ROOM_MEMBER;
CREATE TABLE ROOM_MEMBER (
     RM_SEQ     INTEGER PRIMARY KEY AUTO_INCREMENT,
     M_ID       VARCHAR(50) NOT NULL,
     R_SEQ      INTEGER NOT NULL,
     PRIMARY KEY(RM_SEQ)
);
CREATE UNIQUE INDEX UK_ROOMMEMBER_MID_RSEQ ON ROOM_MEMBER (M_ID, R_SEQ);

DROP TABLE IF EXISTS SPREAD;
CREATE TABLE SPREAD (
     S_SEQ      INTEGER PRIMARY KEY AUTO_INCREMENT,
     M_ID       VARCHAR(50) NOT NULL,
     R_SEQ      INTEGER NOT NULL,
     AMOUNT     INTEGER NOT NULL,
     PERSONNEL  INTEGER NOT NULL,
     TOKEN      CHAR(3) NOT NULL,
     CREATE_AT  DATETIME NOT NULL,
     EXPIRY_AT  DATETIME NOT NULL,
     PRIMARY KEY(S_SEQ)
);
CREATE UNIQUE INDEX UK_SPREAD_RSEQ_MID ON SPREAD (R_SEQ, M_ID);
CREATE UNIQUE INDEX UK_SPREAD_RSEQ_TOKEN ON SPREAD (R_SEQ, TOKEN);

DROP TABLE IF EXISTS SPREAD_DETAIL;
CREATE TABLE SPREAD_DETAIL (
     SD_SEQ     INTEGER PRIMARY KEY AUTO_INCREMENT,
     S_SEQ      INTEGER NOT NULL,
     ORDER_NO   INTEGER NOT NULL,
     M_ID       VARCHAR(50),
     AMOUNT     INTEGER NOT NULL,
     PRIMARY KEY(SD_SEQ)
);
CREATE UNIQUE INDEX UK_SPREADDETAIL_SSEQ_ORDERNO ON SPREAD_DETAIL (S_SEQ, ORDER_NO);
CREATE INDEX IDX_SPREADDETAIL_SSEQ_MID ON SPREAD_DETAIL (S_SEQ, M_ID);
